apiVersion: v1
kind: Service
metadata:
  name: quizkan-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: quizkan-backend
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: quizkan-backend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: quizkan-backend
    networking.gke.io/managed-certificates: quizkan-backend
    kubernetes.io/ingress.class: "gce"
spec:
  backend:
    serviceName: quizkan-backend
    servicePort: 80