apiVersion: v1
kind: Service
metadata:
  name: quizkan-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: quizkan-frontend
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: quizkan-frontend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: quizkan
    networking.gke.io/managed-certificates: quizkan
    kubernetes.io/ingress.class: "gce"
spec:
  backend:
    serviceName: quizkan-frontend
    servicePort: 80