apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizkan-backend-deployment
  labels:
    app: quizkan-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quizkan-backend
  template:
    metadata:
      labels:
        app: quizkan-backend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: quizkan-backend-gameserver
        image: ghcr.io/zuikaru/quizkan-backend
        ports: 
          - containerPort: 8000
        env:
          - name: MODE
            value: "lobby"
          - name: FIREBASE_ADMIN_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: quizkan-frontend-secret
                key: FIREBASE_ADMIN_PRIVATE_KEY
                optional: true
          - name: FIREBASE_ADMIN_CLIENT_EMAIL
            value: "firebase-adminsdk-if1a7@quizkan-game.iam.gserviceaccount.com"
          - name: FIREBASE_ADMIN_CLIENT_EMAIL
            valueFrom: 
              configMapKeyRef:
                name: quizkan-backend-config
                key: FIREBASE_ADMIN_CLIENT_EMAIL
                optional: true
          - name: FIREBASE_ADMIN_PROJECT_ID
            value: "quizkan-game"
          - name: FIREBASE_ADMIN_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: quizkan-backend-config
                key: FIREBASE_ADMIN_PROJECT_ID
                optional: true
          - name: MONGODB_URI
            value: "mongodb://mongo:27017/quizkan"
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: quizkan-backend-secret
                key: MONGODB_URI
                optional: true
          - name: REDIS_ENABLED
            value: "true"
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: quizkan-backend-config
                key: REDIS_HOST
                optional: true
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: quizkan-backend-config
                key: REDIS_PORT
                optional: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        
  