# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   namespace: default
#   name: agones-service
# rules:
# - apiGroups: ["allocation.agones.dev","agones.dev",""] # "" indicates the core API group
#   resources: ["gameserverallocations",""]
#   verbs: ["get", "create", "watch", "list", "update", "patch", "delete"]
# ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agones-service-pod
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: agones-allocator
  apiGroup: rbac.authorization.k8s.io